# Server Configuration
server.port=${PORT:8080}

# H2 Database Configuration (Fallback from MySQL for easy testing)
spring.datasource.url=jdbc:h2:mem:quizdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Custom JWT Properties
jwt.secret=4f71a9a83a00508e31fc54a5c92842e132007e0b57e79cfee513a967f0f62e6
jwt.expirationMs=86400000

# Serve static files
spring.web.resources.static-locations=classpath:/static/
